version: '2'
services: 
        bird-image-detection:
                build: ./bird-image-detection
                privileged: true
                restart: always
                
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'
                environment:
                        - UDEV=1
                devices:
                        - '/dev:/dev'
                ports: 
                        - 4912
        telegram:
                build: ./telegram
                privileged: true
                restart: always
                
                labels:
                        io.balena.features.dbus: '1'
                        io.balena.features.kernel-modules: '1'
                volumes: 
                        - 'shared-data:/var/data'
                        - 'shared-media:/var/media'

volumes:
        shared-data:
        shared-media:
        